# Make the application available at http://localhost:7070/authserver
server:
  port: 8888

cas:
  server-url-prefix: http://localhost:8080/cas
  server-login-url: http://localhost:8080/cas/login
  client-host-url: http://localhost:8888
  validation-type: cas
